### ISSUE TITLE
Possible to split each page as an image instead of PDF ? 

### ISSUE THREAD

**Issue by deepu** [lbaey/flutter_pdf_split#3]
Hey, Thanks for creating this plugin. 

I am looking for a way to split each pdf into individual images (each pdf page = 1 image) . 
Is it possible to get output format as an Image instead of pdf ?

**Comment by lbaey-mobizel** [comment]
No we really want it to be PDF here, in order to keep the quality while zooming, without pixillation, thanks.
Other plugins may do what you want
