### ISSUE TITLE
[Feature Request] Option to stop splitting on demand & Splitting only selective pages

### ISSUE THREAD

**Issue by bluntmess** [lbaey/flutter_pdf_split#7]
Features like stopping splitting and Splitting only selective pages are very much useful in apps. 

Thank you.

**Comment by lbaey-mobizel** [comment]
Such features would be cool !
Feel free to propose Pull request as I don't have a lot of time to code. I'll be happy to review, though.

**Comment by chaudharydeepanshu** [comment]
If anybody is still facing this issue then they may give try to [pdf_manipulator](https://pub.dev/packages/pdf_manipulator) plugin as it supports various sorts of splitting by size(like certain MB), page ranges, page numbers, or certain intervals.
